spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_order_db
spring.datasource.username=postgres
spring.datasource.password=Dhrumil2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
server.port=8081
spring.application.name=order-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
resilience4j.circuitbreaker.instances.inventoryService.sliding-window-size=5
resilience4j.circuitbreaker.instances.inventoryService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventoryService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.inventoryService.permitted-number-of-calls-in-half-open-state=3
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Forces Spring Boot to explicitly initialize Kafka even if cloud config components delay it
spring.autoconfigure.exclude=

# Allow dynamic multi-event deserialization using headers
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# spring.kafka.consumer.properties.spring.json.value.default.type=com.ecommerce.orderservice.event.PaymentCompletedEvent
# spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.consumer.group-id=order-payment-group

# Ensure BOTH of these serializer lines are present and spelled correctly:
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Consumer Type Mappings
spring.kafka.consumer.properties.spring.json.type.mapping=paymentCompletedEvent:com.ecommerce.orderservice.event.PaymentCompletedEvent,paymentFailedEvent:com.ecommerce.orderservice.event.PaymentFailedEvent,inventoryFailedEvent:com.ecommerce.orderservice.event.InventoryFailedEvent

# Producer Type Mappings
spring.kafka.producer.properties.spring.json.type.mapping=orderCreatedEvent:com.ecommerce.orderservice.event.OrderCreatedEvent

# Distributed Tracing & Zipkin Configuration
management.endpoints.web.exposure.include=*
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
spring.zipkin.base-url=http://localhost:9411/
spring.zipkin.baseUrl=http://localhost:9411/

# Enable Kafka Tracing Observation Propagation
spring.kafka.listener.observation-enabled=true
spring.kafka.template.observation-enabled=true

# Logging Pattern with Trace ID and Span ID
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]



