spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_inventory_db
spring.datasource.username=postgres
spring.datasource.password=Dhrumil2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082

spring.application.name=inventory-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.config.import=optional:configserver:http://localhost:8888

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=inventory-group

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# 1. Trust all packages
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# 2. Tell the listener exactly what target class object to turn the JSON into
spring.kafka.consumer.properties.spring.json.value.default.type=com.ecommerce.inventoryservice.event.OrderCreatedEvent

# 3. CRITICAL: Force the consumer to IGNORE the class headers sent by order-service
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# 1. Trust all packages

# 2. REMOVE or COMMENT OUT the single strict default type line so it can accept multiple event classes dynamically:
# spring.kafka.consumer.properties.spring.json.value.default.type=com.ecommerce.inventoryservice.event.OrderCreatedEvent

# 3. CRITICAL: Turn type headers back to TRUE so Kafka can use the class metadata to decide which event object to build

# 3. CRITICAL: Map class header tokens to your local object versions so it switches types instantly!
spring.kafka.consumer.properties.spring.json.type.mapping=orderCreatedEvent:com.ecommerce.inventoryservice.event.OrderCreatedEvent,paymentFailedEvent:com.ecommerce.inventoryservice.event.PaymentFailedEvent
